plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alphalee.kodakdock'
    compileSdk 34

    signingConfigs {
        dock {
            storeFile file('kodak-dock.keystore')
            storePassword 'kodakdock'
            keyAlias 'kodakdock'
            keyPassword 'kodakdock'
        }
    }

    defaultConfig {
        applicationId 'com.alphalee.kodakdock'
        minSdk 26
        targetSdk 27
        versionCode 4
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.dock
        }
    }
}
